export const movie = [
    {
      id: 'bi-mat-cua-gio',
      title_eng: 'Secrets of the Wind',
      title_vn: 'Bí Mật Của Gió',
      title_cn: '祕密𧵑𩙋',
      year: '2020',
      synopsis: '',
      genre: ['romance', 'drama'],
      cast: ['Khả Ngân', 'Trần Quốc Anh', 'Hoàng Yến Chibi'],
      poster: '/poster.jpg',
      featured: true
    },
    {
      id: 'me-chong',
      title_eng: 'Mother-in-Law',
      title_vn: 'Mẹ Chồng',
      title_cn: '媄𫯳',
      year: '2017',
      genre: ['drama'],
      cast: ['Thanh Hằng', 'Midu', 'Song Luân', 'Lâm Vinh Hải'],
      poster: '/poster.jpg',
    },
    {
      id: 'sai-gon-trong-con-mua',
      title_eng: 'Saigon in the Rain',
      title_vn: 'Sài Gòn Trong Cơn Mưa',
      title_cn: '柴棍𥪝𩂀𩄎',
      year: '2020',
      genre: ['romance', 'drama'],
      cast: ['Hồ Thu Anh', 'Avin Lu', 'Hồ Thành Trung'],
      poster: '/poster.jpg',
    },
    {
      id: 'nguoi-bat-tu',
      title_eng: 'The Immortal',
      title_vn: 'Người Bất Tử',
      title_cn: '𠊛不死',
      year: '2018',
      genre: ['drama, fantasy, thriller'],
      cast: ['Quách Ngọc Ngoan', 'Ngọc Diệp', 'Jun Vũ', 'Lâm Vissay', 'Thanh Tú'],
      poster: '/poster.jpg',
    },
    {
      id: 'nham-mat-thay-mua-he',
      title_eng: 'Summer in Closed Eyes',
      title_vn: 'Nhắm Mắt Thấy Mùa Hè',
      title_cn: '𪾮眜𧡊务𢇱',
      year: '2018',
      genre: ['romance', 'drama'],
      cast: ['Phương Anh Đào'],
      poster: '/poster.jpg',
    },
  ]